# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Xu Kaixin's - Homepage"
description              : "A*STAR & NTU"
repository               : "xuk114/xuk114.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      : G-M559P3HC5C # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification : LhwSzN-Db3SDHueApC16Q5C__Y_woIs5Rec1HXUfxbQ  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   : 20151274484837A47E99F3E609F165F6 # get bing_site_verification from https://www.bing.com/webmasters/about
# baidu_site_verification  : codeva-cVScaZuOVg # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Xu Kaixin (徐凯昕)"
  avatar           : "images/profile.png"
  bio              : "Senior Research Engineer in I2R, A*STAR. Part-time Ph.D candidate at NTU. Focusing on model compression."
  location         : "Singapore"
  employer         : "I2R, A*STAR"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=NBIqaHQAAAAJ"
  email            : "xuk@i2r.a-star.edu.sg"
  researchgate     : 
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "Akimoto-Cris"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "kaixin-xu"
  dblp             : "https://dblp.org/pid/16/3309.html"
  orcid            : "https://orcid.org/0000-0002-7222-2628"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :



# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
  - google_scholar_crawler
  - github_myprofile_updater
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Singapore # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
